# Songpress++ colour theme
# Name    : Preferito3
# Saved   : 2026-04-05 15:31
# Version : 1.0
#
# This file can be edited manually.
# Place it in templates/themes/ to make it available in Songpress++.
#
[colours]
bg = #FFFFFF
sel = #C0C0C0
capeditor = #808080
cappreview = #9FCDFB
syntax_normal = #000000
syntax_chorus = #000000
syntax_chord = #FF0000
syntax_command = #0000FF
syntax_attr = #008000
syntax_comment = #808080
syntax_tabgrid = #8B5A00

