# Songpress++ colour theme
# Name    : Grigio_scuro
# Saved   : 2026-05-12 22:07
# Version : 1.0
#
# This file can be edited manually.
# Place it in templates/themes/ to make it available in Songpress++.
#
[colours]
bg = #2B2B2B
sel = #FF80C0
caret = #FFFFFF
capeditor = #808080
cappreview = #9FCDFB
syntax_normal = #D4D4D4
syntax_chorus = #E5C07B
syntax_chord = #E06C75
syntax_command = #61AFEF
syntax_attr = #98C379
syntax_comment = #7F848E
syntax_tabgrid = #BE9A52
