# Songpress++ colour theme
# Name    : Scuro
# Saved   : 2026-05-12
# Version : 1.0
#
# This file can be edited manually.
# Place it in templates/themes/ to make it available in Songpress++.
#
[colours]
bg = #1E1E1E
sel = #264F78
capeditor = #808080
cappreview = #9FCDFB
syntax_normal = #CCCCCC
syntax_chorus = #7EC8E3
syntax_chord = #FF7B72
syntax_command = #79C0FF
syntax_attr = #7EE787
syntax_comment = #8B949E
syntax_tabgrid = #C9A04A
