# Songpress++ colour theme
# Name    : Solarizzato
# Saved   : 2026-05-12
# Version : 1.0
#
# This file can be edited manually.
# Place it in templates/themes/ to make it available in Songpress++.
#
[colours]
bg = #002B36
sel = #073642
capeditor = #808080
cappreview = #9FCDFB
syntax_normal = #839496
syntax_chorus = #2AA198
syntax_chord = #DC322F
syntax_command = #268BD2
syntax_attr = #859900
syntax_comment = #586E75
syntax_tabgrid = #B58900
